# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
  except:
    - gh-pages

environment:
  matrix:
    - {SYSTEM: cygwin, ARCH: x86, COMPILER: 4.02}
    - {SYSTEM: mingw, ARCH: x86_64, COMPILER: 4.03}

install:
  - 'IF "%ARCH%"=="x86" (SET CYG_ROOT=C:\Cygwin) ELSE (SET CYG_ROOT=C:\Cygwin64)'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/$env:SYSTEM/$env:ARCH/ocaml/$env:COMPILER/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/$env:SYSTEM/$env:ARCH/opam/1.2/install.ps1") | PowerShell -Command -'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - '%CYG_ROOT%\bin\bash -lc "echo \"OCaml version `ocamlc -version`\""'

build_script:
  - 'echo Build in "%APPVEYOR_BUILD_FOLDER%"'
  - '%CYG_ROOT%/bin/bash -l "%APPVEYOR_BUILD_FOLDER%/src/tools/ci/appveyor.bash"'

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/7ff53153d7d00ed61e3d
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

artifacts:
  - path: setup.log
    name: setup.log
