OPAM_PKGS=()
OPAM_PKGS+=( "base-bytes")
OPAM_PKGS+=( "base-unix" )
OPAM_PKGS+=( "ocamlfind>=1.3.1" )
OPAM_PKGS+=( "pcre" )
OPAM_PKGS+=( "expect>=0.0.4" )
OPAM_PKGS+=( "fileutils>=0.4.2" )
OPAM_PKGS+=( "ounit>=2.0.0" )
OPAM_PKGS+=( "ocamlify" )
OPAM_PKGS+=( "ocamlmod" )
OPAM_PKGS+=( "omake.0.9.8.6-0.rc1" )
OPAM_PKGS+=( "benchmark>=1.2" )
OPAM_PKGS+=( "camlp4" )
