
(** File generated using environment variables
   
    This is the same kind of file as .in file for autoconf, except we
    use the variable definition of [Buffer.add_substitute]. This is 
    the default file to be generated by configure step (even for 
    autoconf, except that it produce a master file before).

    The file must end with '.ab'.

    @author Sylvain Le Gall
  *)

open OASISTypes

(** Compute the target filename of an .ab file.
  *)
val to_filename : unix_filename -> host_filename

(** Replace variable in file %.ab to generate %.
  *)
val replace : unix_filename list -> unit
