
# AUTOBUILD_START 

SETUP = ocaml setup.ml

BUILDFLAGS     =
DOCFLAGSi      =
TESTFLAGS      =
CLEANFLAGS     =
DISTCLEANFLAGS =


build:
	$(SETUP) -build $(BUILDFLAGS)

doc:
	$(SETUP) -doc $(DOCFLAGS)

test:
	$(SETUP) -test $(TESTFLAGS)

clean:
	$(SETUP) -clean $(CLEANFLAGS)

distclean:
	$(SETUP) -distclean $(DISTCLEANFLAGS)

# AUTOBUILD_STOP 
